// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smhitelagngvjjeuvxoy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtaGl0ZWxhZ25ndmpqZXV2eG95Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NjAzODMsImV4cCI6MjA2MjQzNjM4M30.2RgDBbxflZcTh-ULfQ6SPULAhgTii93BVRL5X-8DUNY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);